export {
  HeaderOne,
  HeaderTwo,
  HeaderThree,
  HeaderFour,
  HeaderFive,
  BodyOne,
  BodyTwo,
  BodyFive,
  BodyFour,
  BodyThree,
  SubTextOne,
  SubTextTwo,
  LargeButtonPureText,
  LargeButtonActiveText,
  LargeButtonInactiveText,
  SmallButtonPureText,
  SmallButtonActiveText,
  SmallButtonInactiveText,
  DropDownText,
  Underline,
} from './common';
